pipeline {
    agent any

    environment {
        AWS_REGION = 'us-west-2'  // Set your AWS region
        TF_VAR_file = 'instances.tfvars'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/your-repo/terraform-backup-plan.git'
            }
        }

        stage('Terraform Init') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-id']]) {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-id']]) {
                    sh 'terraform plan -var-file="${TF_VAR_file}" -out=tfplan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-credentials-id']]) {
                    sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }
}
